version: "3.8"

services:
  app:
    build: .
    container_name: nextBridge-app
    ports:
      - "${PORT}:${PORT}"
    environment:
      - NODE_ENV=production
      - PORT=5061
    restart: unless-stopped
    networks:
      - default

networks:
  default:
    driver: bridge
